10s checking

diff --git a/.github/workflows/genesis-verify.yml b/.github/workflows/genesis-verify.yml
--- a/.github/workflows/genesis-verify.yml
+++ b/.github/workflows/genesis-verify.yml
@@ -51,5 +51,11 @@ jobs:
         run: |
           for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
             echo "Running gnoland with $file"
-            gnoland start -lazy=true --genesis $file
+            timeout 10s gnoland start -lazy=true --genesis $file || exit_code=$?
+            if [ $exit_code -ne 124 ]; then
+              echo "Gnoland run successfully for 10 seconds"
+            else
+              echo "Gnoland failed to start with $file"
+              exit 1
+            fi
           done
